---
- name: Create dummy network interface with nmcli
  hosts: all
  become: true
  tasks:

    - name: Ensure NetworkManager is installed
      apt:
        name: network-manager
        state: present
        update_cache: true

    - name: Add dummy interface using nmcli
      command: >
        nmcli con add type dummy con-name fake ifname fake0 ip4 192.0.2.2/28 gw4 192.0.2.1
      args:
        creates: /etc/NetworkManager/system-connections/fake.nmconnection

    - name: Bring up the dummy interface
      command: nmcli con up fake
