---
- name: Install LXQt desktop with base apps
  hosts: "{{ target_hosts | default('localhost') }}"
  become: true
  connection: local

  tasks:
    - name: Ensure APT cache is updated
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install LXQt desktop environment and base applications
      apt:
        name:
          - lxqt-core           # Minimal LXQt environment
          - lightdm             # Lightweight display manager
          - lxqt-panel          # Panel/taskbar
          - lxqt-session        # Session manager
          - lxqt-runner         # Application launcher
          - pcmanfm-qt          # File manager
          - lxqt-policykit      # PolicyKit integration
          - lxqt-sudo           # GUI sudo
          - lxterminal          # Terminal emulator
          - firefox             # Browser
          - xrdp                # RDP access
        state: present

    - name: Enable graphical target by default
      systemd:
        name: graphical.target
        enabled: true

    - name: Set system to boot into graphical target
      command: systemctl set-default graphical.target
      changed_when: false
