---
- name: Install Portainer
  hosts: localhost
  become: true
  tasks:
    - name: Check if Docker is installed
      command: docker --version
      register: docker_installed
      ignore_errors: yes

    - name: Fail if Docker is not installed
      fail:
        msg: "Docker is not installed. Please install Docker before running this playbook."
      when: docker_installed.failed

    - name: Create Portainer data volume
      docker_volume:
        name: portainer_data
        state: present
      when: not docker_installed.failed

    - name: Pull the latest Portainer image
      docker_image:
        name: portainer/portainer-ce
        tag: latest
        state: present
        force_pull: yes
        source: pull
      when: not docker_installed.failed


    - name: Run Portainer container
      docker_container:
        name: portainer
        image: portainer/portainer-ce:latest
        state: started
        restart_policy: always
        published_ports:
          - "8000:8000"
          - "9443:9443"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data
      when: not docker_installed.failed
