---
- name: Install Portainer
  hosts: localhost
  become: true
  tasks:
    - name: Check if Docker is installed
      command: docker --version
      register: docker_installed
      ignore_errors: yes

    - name: Fail if Docker is not installed
      fail:
        msg: "Docker is not installed. Please install Docker before running this playbook."
      when: docker_installed.failed

    - block:
        - name: Create Portainer data volume
          community.docker.docker_volume:
            name: portainer_data
            state: present

        - name: Run Portainer container
          community.docker.docker_container:
            name: portainer
            image: portainer/portainer-ce:2.33.1
            image_name_mismatch: recreate   # prevent deprecation warning
            pull: yes                       # always pull latest matching tag
            state: started
            restart_policy: always
            published_ports:
              - "8000:8000"
              - "9443:9443"
            volumes:
              - /var/run/docker.sock:/var/run/docker.sock
              - portainer_data:/data
      when: not docker_installed.failed

