---
- name: Install Portainer
  hosts: localhost
  become: true
  tasks:
    - name: Ensure Docker SDK for Python is installed
      package:
        name: python3-docker
        state: present

    - name: Check if Docker is installed
      command: docker --version
      register: docker_installed
      ignore_errors: yes

    - name: Fail if Docker is not installed
      fail:
        msg: "Docker is not installed. Please install Docker before running this playbook."
      when: docker_installed.failed

    - block:
        - name: Create Portainer data volume
          community.docker.docker_volume:
            name: portainer_data
            state: present

        - name: Run Portainer
          community.docker.docker_container:
            name: portainer
            image: portainer/portainer-ce:lts
            state: started
            restart_policy: always
            pull: true
            recreate: true
            comparisons:
              image: strict
            container_default_behavior: compatibility
            ports:
              - "8000:8000"
              - "9443:9443"
            volumes:
              - /var/run/docker.sock:/var/run/docker.sock
              - portainer_data:/data
      when: not docker_installed.failed
