---
# Adapted from an original example by Vivek Gite (nixCraft)
# Source: https://www.cyberciti.biz/faq/ansible-reboot-debian-ubuntu-linux-for-kernel-update-waitforit/
- name: System upgrade and conditional reboot
  hosts: "{{ target_hosts | default('localhost') }}"
  become: true
  connection: local

  tasks:
    - name: Update all packages (dist upgrade)
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Reboot if required
      shell: sleep 10 && /sbin/shutdown -r now 'Rebooting after upgrade'
      args:
        removes: /var/run/reboot-required
      async: 300
      poll: 0
      ignore_errors: true

    - name: Display kernel version
      command: uname -mrs
      register: uname_result

    - debug:
        var: uname_result.stdout_lines




