---
- name: System upgrade and reboot
  hosts: "{{ target_hosts | default('localhost') }}"
  become: true
  connection: local

  tasks:
    - name: Update APT cache
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Perform full system upgrade
      apt:
        # 'dist' performs a full upgrade, including kernel and major system packages
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Reboot after upgrade
      reboot:
        msg: "Rebooting after full system upgrade"
        pre_reboot_delay: 5
        post_reboot_delay: 10
        reboot_timeout: 600

